### ISSUE TITLE
Needs an update

### ISSUE THREAD

**Issue by Texbio** [stuin/RoughlySearchable#2]
I get an error in my chat logs when launching the mod but the mod still works fine:

Mod roughlysearchable provides a broken implementation of ModMenuApi
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'modmenu' provided by 'roughlysearchable'
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:193)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$2(ModMenu.java:73)
	at java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:69)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.client.MinecraftClient.redirect$bag000$catchFabricInit(MinecraftClient:7564)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:457)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: net.fabricmc.loader.api.LanguageAdapterException: Class me.shedaniel.rei.REIModMenuEntryPoint cannot be cast to com.terraformersmc.modmenu.util.ModMenuApiMarker!
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:63)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	... 17 more

This error should not affect the mod at all game-play wise and it still works like a charm.
Also I am using RoughlyEnoughItems-6.0.262-alpha-fabric.jar since the newer versions of rei break the mod.

**Comment by stuin** [comment]
I will look into it, I should be able to update it to a newer version of REI sometime this weekend.

**Comment by stuin** [comment]
Sorry about the wait, should be fixed now
